# plugin.yaml
name: SimpleCDN
version: 1.0
author: YourName
description: 极简腾讯云CDN刷新插件
entry_point: main.py
config_schema:
  secret_id:
    type: string
    label: 腾讯云SecretId
  secret_key:
    type: string
    label: 腾讯云SecretKey
    input_type: password
commands:
  - name: cdn
    description: CDN缓存管理
    usage: |
      /cdn <链接...> [--preheat]
      示例：
      /cdn example.com/static/ --preheat
      /cdn example.com/image.jpg

